const projects = [
{title:'PICEUS Console',category:'Platforms',label:'Command & orchestration',code:'CORE',color:'#4bddd8',summary:'A shared command surface for agents, workflows, identity, and decision intelligence.',detail:'The PICEUS console brings the ecosystem into a coordinated environment. Its architecture connects agent roles, permissions, training history, performance, data, and workflows with enterprise oversight.',points:['Agent workforce coordination and role-based access','Multimodal pipelines and enterprise integrations','Governance, traceability, and human oversight']},
{title:'AgentPing Wallet',category:'Platforms',label:'Identity & transactions',code:'PING',color:'#b49cf4',summary:'An agent-aware wallet and transaction layer for identity, payments, and authorized interaction.',detail:'AgentPing connects wallet activity with identity and permission-aware agent interaction. It extends the PingTone transaction concepts across payments, offers, commerce, and anomaly awareness.',points:['Wallets, payments, and intelligent transactions','Identity and authorized agent interaction','Offers, commerce, and anomaly awareness']},
{title:'StarMetal',category:'Research',label:'Intelligent badge system',code:'STAR',color:'#ffa57e',summary:'A digital badge for law enforcement and other badge-based roles, connected to a dedicated AI agent.',detail:'StarMetal is the wearable badge application within a broader governed intelligence architecture. Research explores vision, facial and voice recognition, biometric and environmental sensing, translation, geospatial awareness, and coordinated response across people and connected assets.',points:['Digital identity, role-based permissions, and a dedicated agent','Health-related telemetry and field awareness','Evidence governance, encryption, Zero Trust, and human oversight']},
{title:'GameBird / GameMax',category:'Experiences',label:'Sports & intelligent play',code:'PLAY',color:'#8fd9a0',summary:'Connected shooting-sports experiences spanning ranges, players, scoring, and competition.',detail:'The GameMax lineage continues through GameBird, connecting sports operations with player experiences. The product direction includes smart cameras and traps, training, memberships, scheduling, score tracking, commerce, and competition.',points:['Range operations, memberships, and scheduling','Player profiles, scoring, and training','Research directions in VR and non-ammunition play']},
{title:'The Tone Knows / TONE',category:'Experiences',label:'Frequency & digital engagement',code:'TONE',color:'#f8ce81',summary:'QR and frequency-based digital experiences connecting physical environments with interaction.',detail:'PICEUS developed an in-vehicle QR and frequency-based digital experience through The Tone Knows, designed for a Hertz rental vehicle use case. Related PingTone work extends into wallet and payment concepts.',points:['In-vehicle digital experience design','QR and frequency-based engagement','Related PingTone wallet and transaction concepts']},
{title:'BuzzVibe',category:'Experiences',label:'Culture & creative community',code:'VIBE',color:'#f398ba',summary:'A creative ecosystem bringing social connection, music, art, fashion, and commerce together.',detail:'BuzzVibe connects a social system and marketplace with creative studios, music production, podcasting, and fashion exchange. BuzzVibe Hollywood and BuzzVibe Studios bring artists, musicians, designers, and communities into the same creative orbit.',points:['Social community and creative marketplace','Music, podcasting, and studio production','Fashion, art, and community collaboration']},
{title:'MATRIX / Church of Matrix',category:'Experiences',label:'Personal systems & exploration',code:'MTRX',color:'#d4b24a',summary:'Personal intelligence, community, and creation-centered exploration in a connected environment.',detail:'MATRIX encompasses the Private Life Console, Matrix Social, and Church of Matrix. The work brings personal systems and community into conversation with mathematical, philosophical, and creation-centered explorations of reality.',points:['Private Life Console and Matrix Social','Community and personal intelligence','Church of Matrix and creation-centered exploration']},
{title:'Brahma',category:'Platforms',label:'Creative intelligence',code:'BRHM',color:'#c1a1f5',summary:'The creative layer within PICEUS, connecting original thinking with the wider intelligence ecosystem.',detail:'Brahma is the named creative layer within the PICEUS architecture. It connects creative exploration to the larger ecosystem of agents, multimodal systems, and human-directed experiences.',points:['Creative layer within the PICEUS ecosystem','Connection to multimodal intelligence','Human-directed creative exploration']},
{title:'TELEPATHY',category:'Research',label:'Machine-native communication',code:'TLPY',color:'#52d8f5',summary:'A machine-native spatiotemporal framework for humans, AI, and autonomous systems.',detail:'TELEPATHY investigates communication, transport, synchronization, and distributed intelligence across optical, electrical, frequency, tactile, and temporal channels. Advanced extensions remain conceptual or experimental where not validated.',points:['Multimodal signaling and synchronization','Spatial and temporal representations','Distributed intelligence and autonomous systems']},
{title:'NAIL',category:'Research',label:'Native AI Language',code:'NAIL',color:'#a0b7ff',summary:'A proposed language layer built around mathematical, spatial, temporal, and signal-based representations.',detail:'NAIL — Native AI Language — is a research direction for representing intent, state, and context among agents, autonomous systems, sensors, and robotics. The proposed layer explores machine-native representations beyond natural-language-only exchanges.',points:['Mathematical and algorithmic representations','Spatial, temporal, and signal-based context','Communication across agents, sensors, and robotics']},
{title:'Braille + Morse Lightning',category:'Research',label:'Multimodal signal systems',code:'· —',color:'#f7cb81',summary:'Complementary touch, light, sound, and frequency concepts for human–machine communication.',detail:'Braille Lightning / Braille 3D explores translating spatial context into touch, haptics, light, sound, and frequency. Morse Lightning / Morse Laser explores encoding human intent in Morse-style optical, audio, and frequency signals. Together they form a complementary research direction within the communication ecosystem.',points:['Spatial context and haptic representations','Morse-style optical and audio signaling','Accessible multimodal communication']},
{title:'AI Matrix Equation',category:'Research',label:'Measurement & governance',code:'AI =',color:'#c8d986',summary:'A framework for observable AI behavior, accountability, system health, and longitudinal evaluation.',detail:'The AI MATRIX EQUATION and Matrixometer explore measurement across physical, computational, and alignment-frequency layers. The framework focuses on observable behavior, measurable consequences, anti-sycophancy, system health, and benefits to people.',points:['Longitudinal evaluation and resistance to reward hacking','Observable behavior rather than unproven human-like states','Badges, achievements, and progress milestones']},
{title:'PickleZone',category:'Experiences',label:'Sports & immersive experiences',code:'PZ',color:'#85dfb1',summary:'Connected pickleball experiences exploring player communities, competition, and immersive play.',detail:'PickleZone work spans player personas, community participation, leagues, and immersive court experiences. Product concepts connect local play with national and international competition, digital rewards, and esports directions.',points:['Player communities and competition','Immersive court and VR concepts','Rewards and participation experiences']},
{title:'PieMaker',category:'Platforms',label:'Personal analytics',code:'PIE',color:'#ffb3a1',summary:'A personal dashboard for seeing how time and energy are allocated across the things that matter.',detail:'PieMaker uses editable indicators, a phone-style percentage dial pad, pie-chart analytics, and a dashboard card to visualize how a person allocates time or energy. The interface shell supports exploration of changing allocations.',points:['Flexible indicator sets and percentage entry','Real-time allocation visualization','Personal analytics and dashboard interface']},
{title:'Distributed AI & Energy',category:'Research',label:'Future infrastructure',code:'GRID',color:'#80cce4',summary:'Research into intelligence beyond the data center and adaptive use of environmental energy.',detail:'This research direction asks how intelligence could operate across distributed environments while improving resource use. Concepts explore thermal recovery, adaptive energy systems, atmospheric and electrostatic charge, and other environment-dependent sources. These are exploratory directions rather than demonstrated energy-performance claims.',points:['Distributed and substrate-independent intelligence concepts','Energy balance, resource use, and thermal recovery','Environmental energy harvesting research']}
];
const grid=document.getElementById('project-grid');
const dialog=document.getElementById('detail');
const content=document.getElementById('dialog-content');
let lastFocus;
function render(filter='All') { const selected=projects.map((p,i)=>({...p,i})).filter(p=>filter==='All'||p.category===filter); grid.innerHTML=selected.map(p=>`<article class="project"><div class="project-visual" style="--accent:${p.color}"><span class="visual-label">PICEUS / ${p.label.toUpperCase()}</span><span class="project-code">${p.code}</span></div><div class="project-body"><div class="meta">${p.category} / ${p.label}</div><h3>${p.title}</h3><p>${p.summary}</p><button data-project="${p.i}" aria-label="Explore ${p.title}">Explore project</button></div></article>`).join(''); document.getElementById('result-count').textContent=`${selected.length} projects`; }
function show(markup){lastFocus=document.activeElement;content.innerHTML=markup;dialog.showModal();}
render();
grid.addEventListener('click',e=>{const button=e.target.closest('[data-project]');if(!button)return;const p=projects[Number(button.dataset.project)];show(`<div class="dialog-meta">${p.category.toUpperCase()} / ${p.label.toUpperCase()}</div><h2>${p.title}</h2><p>${p.detail}</p><ul>${p.points.map(x=>`<li>${x}</li>`).join('')}</ul><a class="button primary" href="#contact" id="project-contact">Discuss this work</a>`);document.getElementById('project-contact').addEventListener('click',()=>dialog.close());});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});render(b.dataset.filter);}));
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('close',()=>lastFocus?.focus());
const menu=document.getElementById('menu'),nav=document.getElementById('navigation');function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.querySelector('span').textContent='＋';}menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.querySelector('span').textContent=open?'−':'＋';});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)nav.querySelectorAll('a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id));});},{rootMargin:'-20% 0px -60% 0px'});document.querySelectorAll('main>section[id]').forEach(s=>observer.observe(s));
document.getElementById('year').textContent=new Date().getFullYear();
document.getElementById('contact-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const subject=`PICEUS inquiry: ${f.get('interest')}`;const body=`Name: ${f.get('name')}\nEmail: ${f.get('email')}\nInterest: ${f.get('interest')}\n\n${f.get('message')}`;window.location.href=`mailto:william.weems@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;document.getElementById('form-status').textContent='Your email draft is ready in your email app. Review it and send it there. If your email app did not open, use the Contact William Weems link.';});
const legal={privacy:`<div class="dialog-meta">PICEUS / WEBSITE PRIVACY</div><h2>Privacy</h2><p>This website does not include analytics trackers or a server-submitted contact form. Contact information entered here is used in your browser to prepare an email draft; the website does not save those entries.</p><p>If you send an email, your email provider and the recipient’s provider process that message. The website hosting service may process technical request information needed to serve and secure the site.</p><p>For privacy questions, contact William Weems through the contact section.</p>`,terms:`<div class="dialog-meta">PICEUS / WEBSITE TERMS</div><h2>Terms</h2><p>This website provides an overview of PICEUS work, product directions, and research. Descriptions do not constitute a service agreement or guarantee of availability, performance, certification, or grant funding.</p><p>Experimental concepts are identified as research. Any engagement, licensing, or delivery terms must be agreed separately in writing.</p><p>PICEUS branding and original website content are reserved to their respective owners. Referenced third-party names remain the property of their owners.</p>`};document.querySelectorAll('[data-legal]').forEach(b=>b.addEventListener('click',()=>show(legal[b.dataset.legal])));
